import * as React from "react";
import { Metadata } from "next";
import { siteConfig } from "@/config/site";

export const metadata: Metadata = {
  title: "Terms of Service - WealthMaze Calculator Usage Policy",
  description: "Read WealthMaze's Terms of Service. Our calculators provide educational estimates only. Understand permitted use, disclaimers, and your responsibilities.",
  alternates: { canonical: `${siteConfig.url}/terms` },
  openGraph: {
    title: "Terms of Service - WealthMaze",
    description: "WealthMaze calculators provide educational financial estimates. Read our full terms of service before using our tools.",
    url: `${siteConfig.url}/terms`,
    type: "website",
    siteName: "WealthMaze",
  },
  twitter: {
    card: "summary_large_image",
    title: "Terms of Service - WealthMaze",
    description: "WealthMaze calculator terms — educational estimates, not financial advice.",
  },
};

const breadcrumbSchema = JSON.stringify({
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    { "@type": "ListItem", "position": 1, "name": "Home", "item": siteConfig.url },
    { "@type": "ListItem", "position": 2, "name": "Terms of Service", "item": `${siteConfig.url}/terms` },
  ],
});

export default function TermsPage() {
  const lastUpdated = "June 18, 2026";

  return (
    <>
    <article className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-6">
      <header className="border-b border-zinc-150 dark:border-zinc-800 pb-4">
        <h1 className="text-3xl font-extrabold text-zinc-900 dark:text-white">Terms of Service</h1>
        <p className="text-xs text-zinc-400 dark:text-zinc-500 mt-2 font-medium">Last Updated: {lastUpdated}</p>
      </header>

      <section className="space-y-4 text-sm leading-relaxed text-zinc-600 dark:text-zinc-300">
        <p>
          Welcome to <strong>WealthMaze</strong> (accessible from wealthmaze.com). By accessing or using our website, tools, and calculators, you agree to be bound by these Terms of Service. If you do not agree, please do not use our website.
        </p>

        <h2 className="text-lg font-bold text-zinc-800 dark:text-zinc-200 mt-6">1. Permitted Use of Tools</h2>
        <p>
          The calculators, tools, and educational guides available on WealthMaze are provided for personal, non-commercial use only. All outputs, projections, and metrics generated by our calculators are mathematical estimates based on user-supplied assumptions and parameters. They should be used for general educational illustration purposes only.
        </p>

        <h2 className="text-lg font-bold text-zinc-800 dark:text-zinc-200 mt-6">2. No Guarantee of Accuracy</h2>
        <p>
          While we strive to maintain the mathematical accuracy of our formulas and slabs (such as tax regimes and compound calculations), WealthMaze does not guarantee that the calculators or content are free of errors, omissions, or delays. Financial markets, tax regulations, and macroeconomic variables (like inflation rates) change regularly. We make no warranty, express or implied, regarding the accuracy, completeness, or future reliability of the outputs.
        </p>

        <h2 className="text-lg font-bold text-zinc-800 dark:text-zinc-200 mt-6">3. User Responsibility</h2>
        <p>
          You acknowledge that you are solely responsible for your own financial and investment decisions. The tools and educational material on WealthMaze are not a substitute for professional financial, tax, investment, accounting, or legal advice. You should consult a qualified and registered financial advisor, certified public accountant (CPA), or legal professional before entering into any transaction or executing any financial plans.
        </p>

        <h2 className="text-lg font-bold text-zinc-800 dark:text-zinc-200 mt-6">4. Limitation of Liability</h2>
        <p>
          Under no circumstances shall WealthMaze, its operators, authors, or affiliates be liable for any direct, indirect, incidental, special, consequential, or punitive damages, including but not limited to financial losses, investment losses, lost profits, or data loss, arising out of or in connection with your use or inability to use this website, even if advised of the possibility of such damages.
        </p>

        <h2 className="text-lg font-bold text-zinc-800 dark:text-zinc-200 mt-6">5. Revisions and Modifications</h2>
        <p>
          We reserve the right to revise these Terms of Service, along with website features and calculations, at any time without prior notice. By continuing to use the site after any amendments, you agree to comply with the updated terms.
        </p>
      </section>
    </article>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: breadcrumbSchema }} />
    </>
  );
}
